version: "3"
services:
  django:
    build: .
    command: gunicorn
    environment:
      - DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${HOSTNAME}
      - DATABASE_URL=${DJANGO_DATABASE_URL}
      - MICROSOFT_AUTH_CLIENT_ID=${DJANGO_MICROSOFT_AUTH_CLIENT_ID}
      - MICROSOFT_AUTH_CLIENT_SECRET=${DJANGO_MICROSOFT_AUTH_CLIENT_SECRET}
      - MICROSOFT_AUTH_TENANT_ID=${DJANGO_MICROSOFT_AUTH_TENANT_ID}
    volumes:
      - "meetup-data:/data"
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.django.tls.certresolver=letsencrypt

  traefik:
    image: "traefik"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/certs/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs"
volumes:
  meetup-data: {}
  certs: {}