# Generated by Django 3.2.4 on 2021-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('kategorie', models.CharField(choices=[('MITGLIEDERSITZUNG', 'Mitgliedersitzung'), ('SCHULUNG', 'Schulung')], default='MITGLIEDERSITZUNG', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
