# Generated by Django 3.2.8 on 2021-10-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_add_default_value_for_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='allow_excuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='excused',
            field=models.BooleanField(default=False),
        ),
    ]
