# Generated by Django 3.2.4 on 2021-06-30 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0003_meeting_teilnehmer_anwesenheit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anwesenheit',
            new_name='Participant',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='kategorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='anwesend',
            new_name='attendant',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='teilnehmer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='teilnehmer_anwesenheit',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(to='meetup.Participant'),
        ),
    ]
