# Generated by Django 3.2.4 on 2021-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0004_model_in_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
